feat: add source code loader
Abraxas-365/langchain-rust pull request #113
Opened 2024-04-10 12:13 UTC by eng-cc

Add source code loader like https://python.langchain.com/docs/integrations/document_loaders/source_code/

2024-04-10 14:07 UTC, Abraxas-365 commented
Thanks for the contribution! 😄🙌🏽 Please, when you finish fixing those small details, I'll merge.

2024-04-10 19:37 UTC, prabirshrestha requested changes
Looks great! Added few more comments.

2024-04-10 19:37 UTC, prabirshrestha commented on src/document_loaders/dir_loader.rs
> +    for entry in fs::read_dir(dir_path)? {
We should tokio::fs instead of std::fs. Even better if use [Opendal](https://github.com/apache/opendal) so one can run this over remote sources.

2024-04-10 19:37 UTC, prabirshrestha commented on src/document_loaders/source_code_loader/source_code_loader.rs
> +                println!("Loading file: {}", filename);
remove println!

2024-04-10 19:56 UTC, Abraxas-365 requested changes

2024-04-11 06:51 UTC, eng-cc commented on src/document_loaders/source_code_loader/source_code_loader.rs
> +    pub fn new(
> Is there any way we can do something like the other loaders, for example the html one?. Where it uses Reader, so we can send a string or parse a file , or send a from_dir , from_path
> 
> ```rust
> #[derive(Debug, Clone)]
> pub struct HtmlLoader<R> {
>     html: R,
>     url: Url,
> }
> 
> impl HtmlLoader<Cursor<Vec<u8>>> {
>     pub fn from_string<S: Into<String>>(input: S, url: Url) -> Self {
>         let input = input.into();
>         let reader = Cursor::new(input.into_bytes());
>         Self::new(reader, url)
>     }
> }
> 
> impl<R: Read> HtmlLoader<R> {
>     pub fn new(html: R, url: Url) -> Self {
>         Self { html, url }
>     }
> }
> 
> impl HtmlLoader<BufReader<File>> {
>     pub fn from_path<P: AsRef<Path>>(path: P, url: Url) -> Result<Self, LoaderError> {
>         let file = File::open(path)?;
>         let reader = BufReader::new(file);
>         Ok(Self::new(reader, url))
>     }
> }
> ```

I tried to use a reader to implement it, but because the difference between processing a folder and a single file is very large, I ultimately couldn't make it into the same reader. We can use LanguageParser.parse_code to parse string into a Document.

2024-04-11 06:52 UTC, eng-cc commented on Cargo.toml
> +tree-sitter-rust = "0.21"
I will adding this later.

2024-04-11 12:33 UTC, Abraxas-365 commented on README.md
> +            let loader = SourceCodeLoader::new(
Pls modify the readme example

2024-04-11 12:49 UTC, Abraxas-365 requested changes

2024-04-11 12:49 UTC, Abraxas-365 commented on src/document_loaders/source_code_loader/source_code_loader.rs
> +                let mut file = File::open(&path).unwrap();
Can we add the error to loader errors? So we don't
Unwrap and elevate the error?

2024-04-11 12:49 UTC, Abraxas-365 commented on src/document_loaders/source_code_loader/source_code_loader.rs
> +        let files = find_files_with_extension(&self.src, self.dir_loader_options).await;
Is there any way we can have a function loader::from_dir(which is the new function we currently have )and we use this function to get the files 

Then we have a new function which takes a reader.

Then have a function loader::from_string

Because we are transforming the file to a string anyway.

So in this way I can load a string of code instead of needing a file or dir 

Don't know is this make sense 🙌🏽🙌🏽

2024-04-12 02:14 UTC, eng-cc commented on src/document_loaders/source_code_loader/source_code_loader.rs
> +        let files = find_files_with_extension(&self.src, self.dir_loader_options).await;
Good idea ,I will try it.

2024-04-17 11:11 UTC, Abraxas-365 commented
LGTM 🙌🏽🙌🏽

2024-04-17 11:12 UTC, Abraxas-365 approved these changes

2024-04-18 09:32 UTC, eng-cc commented
> LGTM 🙌🏽🙌🏽 , there is an fmt error in the pipeline probably a bad indentation, pls fix it so I can merge 😁😁🙌🏽🙌🏽

Thans for your careful review,The problem of fmt has been fixed. but an error was reported during the build process. It is an unmodified part of this branch. Is there have any good suggestions for solving this problem?

2024-04-18 13:33 UTC, Abraxas-365 commented
> > LGTM 🙌🏽🙌🏽 , there is an fmt error in the pipeline probably a bad indentation, pls fix it so I can merge 😁😁🙌🏽🙌🏽
> 
> Thans for your careful review,The problem of fmt has been fixed. but an error was reported during the build process. It is an unmodified part of this branch. Is there have any good suggestions for solving this problem?

Don't worry. It's an error in the pipe. I'm trying to debug it with no success. For some reason, it works after I delete the cache.

2024-04-18 14:43 UTC, Abraxas-365 commented on src/document_loaders/dir_loader.rs
> +    async fn test_find_files_with_extension() {
I found an error in the test builds; it's regarding the temp directory.

2024-04-19 03:54 UTC, Abraxas-365 approved these changes

2024-04-19 03:54 UTC, merged