Wolfram Tool implementation
Abraxas-365/langchain-rust pull request #43
Opened 2024-03-16 23:56 UTC by Jorgefiestas

Adds a tool to call the wolfram API, more specifically the full results endpoint. Tool returns JSON string with answer pods and sub-pods plain text (See more at [Wolfram Documentation](https://products.wolframalpha.com/api/documentation)).

2024-03-17 02:45 UTC, prabirshrestha commented
@Jorgefiestas can you add a sample on examples folder

2024-03-17 02:51 UTC, prabirshrestha requested changes

2024-03-17 02:51 UTC, prabirshrestha commented on src/tools/wolfram/wolfram.rs
> +    pub fn new(app_id: String) -> Self {
can you alos add `with_app_id`. this can be useful when using `default()`.

2024-03-17 02:51 UTC, prabirshrestha commented on src/tools/wolfram/wolfram.rs
> +            self.app_id,
can we urlencode appid even though it will most likely not be needed. This helps prevent random security issues.

2024-03-17 02:51 UTC, prabirshrestha commented on src/tools/wolfram/wolfram.rs
> +        let response: WolframResponse = serde_json::from_str(&response_text)?;
can we use `.json()` instead of `.text()`?

2024-03-18 02:12 UTC, Abraxas-365 commented
LGTM

2024-03-18 02:41 UTC, merged

2024-03-18 02:41 UTC, prabirshrestha commented
Merged. Thanks!